site_name: Anotações
pages:
- 'index.md'
- Amazon: 'amazon.md'
- Banco de dados: 'banco_de_dados.md'
- Bash: 'bash.md'
- Docker: 'docker.md'
- Git:
  - Geral: 'git/git.md'
  - Branches: 'git/branches.md'
  - History: 'git/history.md'
- Latex: 'latex.md'
- Linux: 'linux.md'
- Perl: 'perl.md'
- Ruby: 'ruby.md'
- Vim: 'vim.md'
theme: readthedocs
