site_name: Anotações
pages:
- 'index.md'
- Amazon: 'amazon.md'
- Banco de dados: 'banco_de_dados.md'
- Bash: 'bash.md'
- Benchmarks: 'benchmarks.md'
- Docker: 'docker.md'
- Firefox: 'firefox.md'
- Git: 'git.md'
- Golang: 'golang.md'
- HTML: 'html.md'
- Latex: 'latex.md'
- Linux: 'linux.md'
- Mercurial: 'mercurial.md'
- Perl: 'perl.md'
- Python: 'python.md'
- Ruby: 'ruby.md'
- Vim: 'vim.md'
theme: readthedocs
