site_name: Anotações
pages:
- 'index.md'
- Amazon: 'amazon.md'
- Banco de dados: 'banco_de_dados.md'
- Benchmarks: 'benchmarks.md'
- Bash: 'bash.md'
- Docker: 'docker.md'
- Firefox: 'firefox.md'
- Git:
  - General: 'git/git.md'
  - Branches: 'git/branches.md'
  - Cleaning: 'git/cleaning.md'
  - Exporting: 'git/exporting.md'
  - History: 'git/history.md'
  - Releasing: 'git/releasing.md'
  - Submodules: 'git/submodules.md'
  - Undoing Mistakes: 'git/undoing.md'
  - Encrypting: 'git/encrypting.md'
- HTML:
  - Hints: 'html/hints.md'
- Latex: 'latex.md'
- Linux:
  - awk: 'linux/awk.md'
  - Deleting: 'linux/deleting.md'
  - Dropxbox: 'linux/dropbox.md'
  - File Handling: 'linux/file_handling.md'
  - Format Conversion: 'linux/format_conversions.md'
  - General: 'linux/index.md'
  - Hardware Info: 'linux/hardware.md'
  - Images: 'linux/images.md'
  - Jq: 'linux/jq.md'
  - Logs: 'linux/logs.md'
  - Monitoring: 'linux/monitoring.md'
  - Network: 'linux/network.md'
  - Pass: 'linux/pass.md'
  - PDF: 'linux/pdf.md'
  - Printer: 'linux/printer.md'
  - Terminal: 'linux/terminal.md'
  - Tmux: 'linux/tmux.md'
  - Upgrading Python: 'linux/upgrading_python.md'
  - Wifi: 'linux/wifi.md'
  - Youtube: 'linux/youtube.md'
- Mercurial: 'mercurial.md'
- Python:
  - General: 'python/index.md'
  - Virtual Environment: 'python/virtualenv.md'
- Perl: 'perl.md'
- Ruby: 'ruby.md'
- Vim: 'vim.md'
theme: readthedocs
