site_name: Anotações
pages:
- 'index.md'
- Amazon: 'amazon.md'
- Banco de dados: 'banco_de_dados.md'
- Benchmarks: 'benchmarks.md'
- Bash: 'bash.md'
- Docker: 'docker.md'
- Git:
  - Geral: 'git/git.md'
  - Branches: 'git/branches.md'
  - History: 'git/history.md'
  - Undoing Mistakes: 'git/undoing.md'
- Latex: 'latex.md'
- Linux:
  - General: 'linux/index.md'
  - Dropxbox: 'linux/dropbox.md'
  - File Handling: 'linux/file_handling.md'
  - Format Conversion: 'linux/format_conversions.md'
  - Logs: 'linux/logs.md'
  - Tmux: 'linux/tmux.md'
  - Youtube: 'linux/youtube.md'
- Python: 'python/index.md'
- Perl: 'perl.md'
- Ruby: 'ruby.md'
- Vim: 'vim.md'
theme: readthedocs
